const products=[{id:1,name:'Oversized T-Shirt',category:'Fashion',price:599,emoji:'👕'},{id:2,name:'Running Shoes',category:'Shoes',price:1499,emoji:'👟'},{id:3,name:'Minimal Watch',category:'Accessories',price:899,emoji:'⌚'},{id:4,name:'Wireless Headphones',category:'Electronics',price:1999,emoji:'🎧'},{id:5,name:'Premium Hoodie',category:'Fashion',price:1199,emoji:'🧥'},{id:6,name:'Everyday Backpack',category:'Accessories',price:799,emoji:'🎒'},{id:7,name:'Smart Sunglasses',category:'Accessories',price:499,emoji:'🕶️'},{id:8,name:'Bluetooth Speaker',category:'Electronics',price:1299,emoji:'🔊'}];
let cart=JSON.parse(localStorage.getItem('cart')||'[]');
function save(){localStorage.setItem('cart',JSON.stringify(cart));updateCount()}
function updateCount(){document.querySelectorAll('#count').forEach(e=>e.textContent=cart.reduce((s,p)=>s+p.qty,0))}
function add(id){let p=products.find(x=>x.id===id),item=cart.find(x=>x.id===id);if(item)item.qty++;else cart.push({...p,qty:1});save();location.href='cart.html'}
function renderProducts(){let box=document.getElementById('products');if(!box)return;let search=(document.getElementById('search')?.value||'').toLowerCase();let category=new URLSearchParams(location.search).get('category');let list=products.filter(p=>(!category||p.category===category)&&(p.name.toLowerCase().includes(search)||p.category.toLowerCase().includes(search)));let sort=document.getElementById('sort')?.value;if(sort==='low')list.sort((a,b)=>a.price-b.price);if(sort==='high')list.sort((a,b)=>b.price-a.price);box.innerHTML=list.map(p=>`<div class="product"><div class="pic">${p.emoji}</div><div class="info"><h3>${p.name}</h3><small>${p.category}</small><div class="price">₹${p.price.toLocaleString('en-IN')}</div><button class="add" onclick="add(${p.id})">Add to Cart →</button></div></div>`).join('')}
function renderCart(){let box=document.getElementById('cartItems');if(!box)return;let total=0;box.innerHTML=cart.length?cart.map(p=>{total+=p.price*p.qty;return `<div class="cart-row"><div class="pic">${p.emoji}</div><div><b>${p.name}</b><p>₹${p.price} × ${p.qty}</p></div><button onclick="removeItem(${p.id})">Remove</button></div>`}).join(''):'<p>Your cart is empty. <a href="shop.html">Go shopping →</a></p>';document.getElementById('total').textContent=total.toLocaleString('en-IN');if(document.getElementById('payTotal'))document.getElementById('payTotal').textContent=total.toLocaleString('en-IN')}
function removeItem(id){cart=cart.filter(p=>p.id!==id);save();renderCart()}
document.getElementById('search')?.addEventListener('input',renderProducts);document.getElementById('sort')?.addEventListener('change',renderProducts);
document.getElementById('paymentForm')?.addEventListener('submit',e=>{e.preventDefault();if(!cart.length){alert('Your cart is empty!');return}alert('Order placed successfully! This is a demo.');cart=[];save();location.href='index.html'});
document.getElementById('contactForm')?.addEventListener('submit',e=>{e.preventDefault();document.getElementById('contactMsg').textContent='Thank you! Your message has been submitted in demo mode.';e.target.reset()});
updateCount();renderProducts();renderCart();